# Site settings
port: 4000
title: propane (Code as Art)
email: mamba2928@yahoo.co.uk
description: > # this means to ignore newlines until "baseurl:"
   propane is a ruby wrapper for processing-3.3.3. For windows user install
   JRubyArt.
baseurl: "" # the subpath of your site, e.g. /blog
regenerate: true
url: "https://ruby-processing.github.io/propane"
urls:
  bugs: http://github.com/ruby-processing/propane/issues
  github: http://github.com/ruby-processing/propane/
twitter_username: monkstoneT
github_username:  monkstone
include: [collections]
collections:
  blocks:
    output: true
    permalink: /blocks/:path
  classes:
    output: true
    permalink: /classes/:path
  editors:
    output: true
    permalink: /editors/:path
  methods:
    output: true
    permalink: /methods/:path
  gems:
    output: true
    permalink: /gems/:path
  libraries:
    output: true
    permalink: /libraries/:path
  modules:
    output: true
    permalink: /modules/:path
  magic:
    output: true
    permalink: /magic/:path
  objects:
    output: true
    permalink: /objects/:path

syntax-highlighting:
  enabled: true

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
